mongo:
  uri: ""
  is-uri: false
  host: localhost
  port: 27017
  database: "Vitality"
  auth: false
  user: "admin"
  password: "12345"
redis:
  host: localhost
  port: 6379
  auth: false
  password: "admin"
maintenance:
  enabled: false
  rank: "Default"
  players: []
motd:
  enabled: false # Do you want Vitality to manage your network MOTD?
  maintenance-enabled: false # Do you want a special MOTD while the network is under maintenance?